INSERT INTO `pais` VALUES (1, 'US', 'United States',1);
INSERT INTO `pais` VALUES (2, 'CA', 'Canada',1);
INSERT INTO `pais` VALUES (3, 'AF', 'Afghanistan',1);
INSERT INTO `pais` VALUES (4, 'AL', 'Albania',1);
INSERT INTO `pais` VALUES (5, 'DZ', 'Algeria',1);
INSERT INTO `pais` VALUES (6, 'DS', 'American Samoa',1);
INSERT INTO `pais` VALUES (7, 'AD', 'Andorra',1);
INSERT INTO `pais` VALUES (8, 'AO', 'Angola',1);
INSERT INTO `pais` VALUES (9, 'AI', 'Anguilla',1);
INSERT INTO `pais` VALUES (10, 'AQ', 'Antarctica',1);
INSERT INTO `pais` VALUES (11, 'AG', 'Antigua and/or Barbuda',1);
INSERT INTO `pais` VALUES (12, 'AR', 'Argentina',1);
INSERT INTO `pais` VALUES (13, 'AM', 'Armenia',1);
INSERT INTO `pais` VALUES (14, 'AW', 'Aruba',1);
INSERT INTO `pais` VALUES (15, 'AU', 'Australia',1);
INSERT INTO `pais` VALUES (16, 'AT', 'Austria',1);
INSERT INTO `pais` VALUES (17, 'AZ', 'Azerbaijan',1);
INSERT INTO `pais` VALUES (18, 'BS', 'Bahamas',1);
INSERT INTO `pais` VALUES (19, 'BH', 'Bahrain',1);
INSERT INTO `pais` VALUES (20, 'BD', 'Bangladesh',1);
INSERT INTO `pais` VALUES (21, 'BB', 'Barbados',1);
INSERT INTO `pais` VALUES (22, 'BY', 'Belarus',1);
INSERT INTO `pais` VALUES (23, 'BE', 'Belgium',1);
INSERT INTO `pais` VALUES (24, 'BZ', 'Belize',1);
INSERT INTO `pais` VALUES (25, 'BJ', 'Benin',1);
INSERT INTO `pais` VALUES (26, 'BM', 'Bermuda',1);
INSERT INTO `pais` VALUES (27, 'BT', 'Bhutan',1);
INSERT INTO `pais` VALUES (28, 'BO', 'Bolivia',1);
INSERT INTO `pais` VALUES (29, 'BA', 'Bosnia and Herzegovina',1);
INSERT INTO `pais` VALUES (30, 'BW', 'Botswana',1);
INSERT INTO `pais` VALUES (31, 'BV', 'Bouvet Island',1);
INSERT INTO `pais` VALUES (32, 'BR', 'Brazil',1);
INSERT INTO `pais` VALUES (33, 'IO', 'British lndian Ocean Territory',1);
INSERT INTO `pais` VALUES (34, 'BN', 'Brunei Darussalam',1);
INSERT INTO `pais` VALUES (35, 'BG', 'Bulgaria',1);
INSERT INTO `pais` VALUES (36, 'BF', 'Burkina Faso',1);
INSERT INTO `pais` VALUES (37, 'BI', 'Burundi',1);
INSERT INTO `pais` VALUES (38, 'KH', 'Cambodia',1);
INSERT INTO `pais` VALUES (39, 'CM', 'Cameroon',1);
INSERT INTO `pais` VALUES (40, 'CV', 'Cape Verde',1);
INSERT INTO `pais` VALUES (41, 'KY', 'Cayman Islands',1);
INSERT INTO `pais` VALUES (42, 'CF', 'Central African Republic',1);
INSERT INTO `pais` VALUES (43, 'TD', 'Chad',1);
INSERT INTO `pais` VALUES (44, 'CL', 'Chile',1);
INSERT INTO `pais` VALUES (45, 'CN', 'China',1);
INSERT INTO `pais` VALUES (46, 'CX', 'Christmas Island',1);
INSERT INTO `pais` VALUES (47, 'CC', 'Cocos (Keeling,1) Islands',1);
INSERT INTO `pais` VALUES (48, 'CO', 'Colombia',1);
INSERT INTO `pais` VALUES (49, 'KM', 'Comoros',1);
INSERT INTO `pais` VALUES (50, 'CG', 'Congo',1);
INSERT INTO `pais` VALUES (51, 'CK', 'Cook Islands',1);
INSERT INTO `pais` VALUES (52, 'CR', 'Costa Rica',1);
INSERT INTO `pais` VALUES (53, 'HR', 'Croatia (Hrvatska,1)',1);
INSERT INTO `pais` VALUES (54, 'CU', 'Cuba',1);
INSERT INTO `pais` VALUES (55, 'CY', 'Cyprus',1);
INSERT INTO `pais` VALUES (56, 'CZ', 'Czech Republic',1);
INSERT INTO `pais` VALUES (57, 'DK', 'Denmark',1);
INSERT INTO `pais` VALUES (58, 'DJ', 'Djibouti',1);
INSERT INTO `pais` VALUES (59, 'DM', 'Dominica',1);
INSERT INTO `pais` VALUES (60, 'DO', 'Dominican Republic',1);
INSERT INTO `pais` VALUES (61, 'TP', 'East Timor',1);
INSERT INTO `pais` VALUES (62, 'EC', 'Ecudaor',1);
INSERT INTO `pais` VALUES (63, 'EG', 'Egypt',1);
INSERT INTO `pais` VALUES (64, 'SV', 'El Salvador',1);
INSERT INTO `pais` VALUES (65, 'GQ', 'Equatorial Guinea',1);
INSERT INTO `pais` VALUES (66, 'ER', 'Eritrea',1);
INSERT INTO `pais` VALUES (67, 'EE', 'Estonia',1);
INSERT INTO `pais` VALUES (68, 'ET', 'Ethiopia',1);
INSERT INTO `pais` VALUES (69, 'FK', 'Falkland Islands (Malvinas,1)',1);
INSERT INTO `pais` VALUES (70, 'FO', 'Faroe Islands',1);
INSERT INTO `pais` VALUES (71, 'FJ', 'Fiji',1);
INSERT INTO `pais` VALUES (72, 'FI', 'Finland',1);
INSERT INTO `pais` VALUES (73, 'FR', 'France',1);
INSERT INTO `pais` VALUES (74, 'FX', 'France, Metropolitan',1);
INSERT INTO `pais` VALUES (75, 'GF', 'French Guiana',1);
INSERT INTO `pais` VALUES (76, 'PF', 'French Polynesia',1);
INSERT INTO `pais` VALUES (77, 'TF', 'French Southern Territories',1);
INSERT INTO `pais` VALUES (78, 'GA', 'Gabon',1);
INSERT INTO `pais` VALUES (79, 'GM', 'Gambia',1);
INSERT INTO `pais` VALUES (80, 'GE', 'Georgia',1);
INSERT INTO `pais` VALUES (81, 'DE', 'Germany',1);
INSERT INTO `pais` VALUES (82, 'GH', 'Ghana',1);
INSERT INTO `pais` VALUES (83, 'GI', 'Gibraltar',1);
INSERT INTO `pais` VALUES (84, 'GR', 'Greece',1);
INSERT INTO `pais` VALUES (85, 'GL', 'Greenland',1);
INSERT INTO `pais` VALUES (86, 'GD', 'Grenada',1);
INSERT INTO `pais` VALUES (87, 'GP', 'Guadeloupe',1);
INSERT INTO `pais` VALUES (88, 'GU', 'Guam',1);
INSERT INTO `pais` VALUES (89, 'GT', 'Guatemala',1);
INSERT INTO `pais` VALUES (90, 'GN', 'Guinea',1);
INSERT INTO `pais` VALUES (91, 'GW', 'Guinea-Bissau',1);
INSERT INTO `pais` VALUES (92, 'GY', 'Guyana',1);
INSERT INTO `pais` VALUES (93, 'HT', 'Haiti',1);
INSERT INTO `pais` VALUES (94, 'HM', 'Heard and Mc Donald Islands',1);
INSERT INTO `pais` VALUES (95, 'HN', 'Honduras',1);
INSERT INTO `pais` VALUES (96, 'HK', 'Hong Kong',1);
INSERT INTO `pais` VALUES (97, 'HU', 'Hungary',1);
INSERT INTO `pais` VALUES (98, 'IS', 'Iceland',1);
INSERT INTO `pais` VALUES (99, 'IN', 'India',1);
INSERT INTO `pais` VALUES (100, 'ID', 'Indonesia',1);
INSERT INTO `pais` VALUES (101, 'IR', 'Iran (Islamic Republic of,1)',1);
INSERT INTO `pais` VALUES (102, 'IQ', 'Iraq',1);
INSERT INTO `pais` VALUES (103, 'IE', 'Ireland',1);
INSERT INTO `pais` VALUES (104, 'IL', 'Israel',1);
INSERT INTO `pais` VALUES (105, 'IT', 'Italy',1);
INSERT INTO `pais` VALUES (106, 'CI', 'Ivory Coast',1);
INSERT INTO `pais` VALUES (107, 'JM', 'Jamaica',1);
INSERT INTO `pais` VALUES (108, 'JP', 'Japan',1);
INSERT INTO `pais` VALUES (109, 'JO', 'Jordan',1);
INSERT INTO `pais` VALUES (110, 'KZ', 'Kazakhstan',1);
INSERT INTO `pais` VALUES (111, 'KE', 'Kenya',1);
INSERT INTO `pais` VALUES (112, 'KI', 'Kiribati',1);
INSERT INTO `pais` VALUES (113, 'KP', 'Korea, Democratic People''s Republic of',1);
INSERT INTO `pais` VALUES (114, 'KR', 'Korea, Republic of',1);
INSERT INTO `pais` VALUES (115, 'KW', 'Kuwait',1);
INSERT INTO `pais` VALUES (116, 'KG', 'Kyrgyzstan',1);
INSERT INTO `pais` VALUES (117, 'LA', 'Lao People''s Democratic Republic',1);
INSERT INTO `pais` VALUES (118, 'LV', 'Latvia',1);
INSERT INTO `pais` VALUES (119, 'LB', 'Lebanon',1);
INSERT INTO `pais` VALUES (120, 'LS', 'Lesotho',1);
INSERT INTO `pais` VALUES (121, 'LR', 'Liberia',1);
INSERT INTO `pais` VALUES (122, 'LY', 'Libyan Arab Jamahiriya',1);
INSERT INTO `pais` VALUES (123, 'LI', 'Liechtenstein',1);
INSERT INTO `pais` VALUES (124, 'LT', 'Lithuania',1);
INSERT INTO `pais` VALUES (125, 'LU', 'Luxembourg',1);
INSERT INTO `pais` VALUES (126, 'MO', 'Macau',1);
INSERT INTO `pais` VALUES (127, 'MK', 'Macedonia',1);
INSERT INTO `pais` VALUES (128, 'MG', 'Madagascar',1);
INSERT INTO `pais` VALUES (129, 'MW', 'Malawi',1);
INSERT INTO `pais` VALUES (130, 'MY', 'Malaysia',1);
INSERT INTO `pais` VALUES (131, 'MV', 'Maldives',1);
INSERT INTO `pais` VALUES (132, 'ML', 'Mali',1);
INSERT INTO `pais` VALUES (133, 'MT', 'Malta',1);
INSERT INTO `pais` VALUES (134, 'MH', 'Marshall Islands',1);
INSERT INTO `pais` VALUES (135, 'MQ', 'Martinique',1);
INSERT INTO `pais` VALUES (136, 'MR', 'Mauritania',1);
INSERT INTO `pais` VALUES (137, 'MU', 'Mauritius',1);
INSERT INTO `pais` VALUES (138, 'TY', 'Mayotte',1);
INSERT INTO `pais` VALUES (139, 'MX', 'Mexico',1);
INSERT INTO `pais` VALUES (140, 'FM', 'Micronesia, Federated States of',1);
INSERT INTO `pais` VALUES (141, 'MD', 'Moldova, Republic of',1);
INSERT INTO `pais` VALUES (142, 'MC', 'Monaco',1);
INSERT INTO `pais` VALUES (143, 'MN', 'Mongolia',1);
INSERT INTO `pais` VALUES (144, 'MS', 'Montserrat',1);
INSERT INTO `pais` VALUES (145, 'MA', 'Morocco',1);
INSERT INTO `pais` VALUES (146, 'MZ', 'Mozambique',1);
INSERT INTO `pais` VALUES (147, 'MM', 'Myanmar',1);
INSERT INTO `pais` VALUES (148, 'NA', 'Namibia',1);
INSERT INTO `pais` VALUES (149, 'NR', 'Nauru',1);
INSERT INTO `pais` VALUES (150, 'NP', 'Nepal',1);
INSERT INTO `pais` VALUES (151, 'NL', 'Netherlands',1);
INSERT INTO `pais` VALUES (152, 'AN', 'Netherlands Antilles',1);
INSERT INTO `pais` VALUES (153, 'NC', 'New Caledonia',1);
INSERT INTO `pais` VALUES (154, 'NZ', 'New Zealand',1);
INSERT INTO `pais` VALUES (155, 'NI', 'Nicaragua',1);
INSERT INTO `pais` VALUES (156, 'NE', 'Niger',1);
INSERT INTO `pais` VALUES (157, 'NG', 'Nigeria',1);
INSERT INTO `pais` VALUES (158, 'NU', 'Niue',1);
INSERT INTO `pais` VALUES (159, 'NF', 'Norfork Island',1);
INSERT INTO `pais` VALUES (160, 'MP', 'Northern Mariana Islands',1);
INSERT INTO `pais` VALUES (161, 'NO', 'Norway',1);
INSERT INTO `pais` VALUES (162, 'OM', 'Oman',1);
INSERT INTO `pais` VALUES (163, 'PK', 'Pakistan',1);
INSERT INTO `pais` VALUES (164, 'PW', 'Palau',1);
INSERT INTO `pais` VALUES (165, 'PA', 'Panama',1);
INSERT INTO `pais` VALUES (166, 'PG', 'Papua New Guinea',1);
INSERT INTO `pais` VALUES (167, 'PY', 'Paraguay',1);
INSERT INTO `pais` VALUES (168, 'PE', 'Peru',1);
INSERT INTO `pais` VALUES (169, 'PH', 'Philippines',1);
INSERT INTO `pais` VALUES (170, 'PN', 'Pitcairn',1);
INSERT INTO `pais` VALUES (171, 'PL', 'Poland',1);
INSERT INTO `pais` VALUES (172, 'PT', 'Portugal',1);
INSERT INTO `pais` VALUES (173, 'PR', 'Puerto Rico',1);
INSERT INTO `pais` VALUES (174, 'QA', 'Qatar',1);
INSERT INTO `pais` VALUES (175, 'RE', 'Reunion',1);
INSERT INTO `pais` VALUES (176, 'RO', 'Romania',1);
INSERT INTO `pais` VALUES (177, 'RU', 'Russian Federation',1);
INSERT INTO `pais` VALUES (178, 'RW', 'Rwanda',1);
INSERT INTO `pais` VALUES (179, 'KN', 'Saint Kitts and Nevis',1);
INSERT INTO `pais` VALUES (180, 'LC', 'Saint Lucia',1);
INSERT INTO `pais` VALUES (181, 'VC', 'Saint Vincent and the Grenadines',1);
INSERT INTO `pais` VALUES (182, 'WS', 'Samoa',1);
INSERT INTO `pais` VALUES (183, 'SM', 'San Marino',1);
INSERT INTO `pais` VALUES (184, 'ST', 'Sao Tome and Principe',1);
INSERT INTO `pais` VALUES (185, 'SA', 'Saudi Arabia',1);
INSERT INTO `pais` VALUES (186, 'SN', 'Senegal',1);
INSERT INTO `pais` VALUES (187, 'SC', 'Seychelles',1);
INSERT INTO `pais` VALUES (188, 'SL', 'Sierra Leone',1);
INSERT INTO `pais` VALUES (189, 'SG', 'Singapore',1);
INSERT INTO `pais` VALUES (190, 'SK', 'Slovakia',1);
INSERT INTO `pais` VALUES (191, 'SI', 'Slovenia',1);
INSERT INTO `pais` VALUES (192, 'SB', 'Solomon Islands',1);
INSERT INTO `pais` VALUES (193, 'SO', 'Somalia',1);
INSERT INTO `pais` VALUES (194, 'ZA', 'South Africa',1);
INSERT INTO `pais` VALUES (195, 'GS', 'South Georgia South Sandwich Islands',1);
INSERT INTO `pais` VALUES (196, 'ES', 'Spain',1);
INSERT INTO `pais` VALUES (197, 'LK', 'Sri Lanka',1);
INSERT INTO `pais` VALUES (198, 'SH', 'St. Helena',1);
INSERT INTO `pais` VALUES (199, 'PM', 'St. Pierre and Miquelon',1);
INSERT INTO `pais` VALUES (200, 'SD', 'Sudan',1);
INSERT INTO `pais` VALUES (201, 'SR', 'Suriname',1);
INSERT INTO `pais` VALUES (202, 'SJ', 'Svalbarn and Jan Mayen Islands',1);
INSERT INTO `pais` VALUES (203, 'SZ', 'Swaziland',1);
INSERT INTO `pais` VALUES (204, 'SE', 'Sweden',1);
INSERT INTO `pais` VALUES (205, 'CH', 'Switzerland',1);
INSERT INTO `pais` VALUES (206, 'SY', 'Syrian Arab Republic',1);
INSERT INTO `pais` VALUES (207, 'TW', 'Taiwan',1);
INSERT INTO `pais` VALUES (208, 'TJ', 'Tajikistan',1);
INSERT INTO `pais` VALUES (209, 'TZ', 'Tanzania, United Republic of',1);
INSERT INTO `pais` VALUES (210, 'TH', 'Thailand',1);
INSERT INTO `pais` VALUES (211, 'TG', 'Togo',1);
INSERT INTO `pais` VALUES (212, 'TK', 'Tokelau',1);
INSERT INTO `pais` VALUES (213, 'TO', 'Tonga',1);
INSERT INTO `pais` VALUES (214, 'TT', 'Trinidad and Tobago',1);
INSERT INTO `pais` VALUES (215, 'TN', 'Tunisia',1);
INSERT INTO `pais` VALUES (216, 'TR', 'Turkey',1);
INSERT INTO `pais` VALUES (217, 'TM', 'Turkmenistan',1);
INSERT INTO `pais` VALUES (218, 'TC', 'Turks and Caicos Islands',1);
INSERT INTO `pais` VALUES (219, 'TV', 'Tuvalu',1);
INSERT INTO `pais` VALUES (220, 'UG', 'Uganda',1);
INSERT INTO `pais` VALUES (221, 'UA', 'Ukraine',1);
INSERT INTO `pais` VALUES (222, 'AE', 'United Arab Emirates',1);
INSERT INTO `pais` VALUES (223, 'GB', 'United Kingdom',1);
INSERT INTO `pais` VALUES (224, 'UM', 'United States minor outlying islands',1);
INSERT INTO `pais` VALUES (225, 'UY', 'Uruguay',1);
INSERT INTO `pais` VALUES (226, 'UZ', 'Uzbekistan',1);
INSERT INTO `pais` VALUES (227, 'VU', 'Vanuatu',1);
INSERT INTO `pais` VALUES (228, 'VA', 'Vatican City State',1);
INSERT INTO `pais` VALUES (229, 'VE', 'Venezuela',1);
INSERT INTO `pais` VALUES (230, 'VN', 'Vietnam',1);
INSERT INTO `pais` VALUES (231, 'VG', 'Virigan Islands (British,1)',1);
INSERT INTO `pais` VALUES (232, 'VI', 'Virgin Islands (U.S.,1)',1);
INSERT INTO `pais` VALUES (233, 'WF', 'Wallis and Futuna Islands',1);
INSERT INTO `pais` VALUES (234, 'EH', 'Western Sahara',1);
INSERT INTO `pais` VALUES (235, 'YE', 'Yemen',1);
INSERT INTO `pais` VALUES (236, 'YU', 'Yugoslavia',1);
INSERT INTO `pais` VALUES (237, 'ZR', 'Zaire',1);
INSERT INTO `pais` VALUES (238, 'ZM', 'Zambia',1);
INSERT INTO `pais` VALUES (239, 'ZW', 'Zimbabwe',1);
INSERT INTO `categoria` VALUES (1,'Automóviles',1);
INSERT INTO `categoria` VALUES (2,'Bebes',1);
INSERT INTO `categoria` VALUES (3,'Belleza',1);
INSERT INTO `categoria` VALUES (4,'Libros',1);
INSERT INTO `categoria` VALUES (5,'Celulares',1);
INSERT INTO `categoria` VALUES (6,'Ropa',1);
INSERT INTO `categoria` VALUES (7,'Arte Fina',1);
INSERT INTO `categoria` VALUES (8,'Computadoras',1);
INSERT INTO `categoria` VALUES (9,'Articulos Eléctronicos',1);
INSERT INTO `categoria` VALUES (10,'Cuidado Personal',1);
INSERT INTO `categoria` VALUES (11,'Cocina',1);
INSERT INTO `categoria` VALUES (12,'Industria',1);
INSERT INTO `categoria` VALUES (13,'Joyería',1);
INSERT INTO `categoria` VALUES (14,'Peliculas',1);
INSERT INTO `categoria` VALUES (15,'Música',1);
INSERT INTO `categoria` VALUES (16,'Instrumentos Músicales',1);
INSERT INTO `categoria` VALUES (17,'Equipo de Oficina',1);
INSERT INTO `categoria` VALUES (18,'Equipo de Jardín',1);
INSERT INTO `categoria` VALUES (19,'Zapatos',1);
INSERT INTO `categoria` VALUES (20,'Software',1);
INSERT INTO `categoria` VALUES (21,'Deportes',1);
INSERT INTO `categoria` VALUES (22,'Herramientas',1);
INSERT INTO `categoria` VALUES (23,'Juegos',1);
INSERT INTO `categoria` VALUES (24,'Relojes',1);
INSERT INTO `usuario` (`id`, `nombre`, `email`, `password`, `activo`, `llave_activacion`, `ulltima_visita`, `cont_fallos`, `bloqueado`, `imagen`, `fecha_creada`) VALUES (1, 'Administrador', 'adminusr@daw.com', '$2a$13$5B9qN3MdKrFARvyHn53.aO3vkjYkHofOJOOWJJpT8grUvefhWrYwi', '1', 'none', '2013-11-12 17:26:10', 0, '0', 'images/usuario/newuser.png', '2013-11-12 17:26:10');
INSERT INTO `ciudad` VALUES (1,'56','Tegucigalpa',1);
INSERT INTO `ciudad` VALUES (2,'56','San Pedro Sula',1);
INSERT INTO `ciudad` VALUES (3,'56','Comayagua',1);
INSERT INTO `ciudad` VALUES (4,'56','Siguatepeque',1);
INSERT INTO `ciudad` VALUES (5,'56','La Cebia',1);